version: '3'
services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_USER: recipe_manager
      MYSQL_PASSWORD: Zxasqw!@
      MYSQL_DATABASE: recipe_manager
      MYSQL_ROOT_PASSWORD: Zxcdsa!@
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached      
    command: sleep infinity
    network_mode: service:db
